// Audio paths for onboarding narration — generated by ElevenLabs.
// All paths are empty until audio files are provided.

export const onboardingAudio = {
  characterSelectIntro: '/Hangok/ValasszHost/mainText.mp3',
  characterIntros: {
    bence:  '/Hangok/ValasszHost/bence.mp3',
    erno:   '/Hangok/ValasszHost/erno.mp3',
    szonja: '/Hangok/ValasszHost/szonja.mp3',
    huba:   '/Hangok/ValasszHost/huba.mp3',
    vanda:  '/Hangok/ValasszHost/vanda.mp3',
    balazs: '/Hangok/ValasszHost/balazs.mp3',
  } as Record<string, string>,
  namingIntro:   '',
  namingConfirm: '',
  screen1:       '',
  screen2:       '',
  screen3: {
    bence:  '',
    erno:   '',
    szonja: '',
    huba:   '',
    vanda:  '',
    balazs: '',
  } as Record<string, string>,
  screen4:       '',
  screen5:       '',
  mapFirstArrival: '',
  hints: {
    mapNextStep:      '',
    chapterIntro:     '',
    firstCoin:        '',
    badgeComplete:    '',
    islandFirstVisit: '',
    islandPlaceItem:  '',
  },
};
