// Audio paths for onboarding narration — generated by ElevenLabs.
// All paths are empty until audio files are provided.

export const onboardingAudio = {
  characterSelectIntro: '',
  characterIntros: {
    bence:  '',
    erno:   '',
    szonja: '',
    huba:   '',
    vanda:  '',
    balazs: '',
  } as Record<string, string>,
  namingIntro:   '',
  namingConfirm: '',
  screen1:       '',
  screen2:       '',
  screen3: {
    bence:  '',
    erno:   '',
    szonja: '',
    huba:   '',
    vanda:  '',
    balazs: '',
  } as Record<string, string>,
  screen4:       '',
  screen5:       '',
  mapFirstArrival: '',
};
